### ISSUE TITLE
Server Logs Errors Dump

### ISSUE THREAD

**Issue by prastut** [buidl-labs/polka-analytics-api#111]
### DB related errors: 

```!
May 16 09:43:47 PM  MongoError: Cache Reader No keys found for HMAC that is valid for time: { ts: Timestamp(1589645567, 1) } with id: 6771397799096352771
    at Connection.<anonymous> (/opt/render/project/src/node_modules/mongodb/lib/core/connection/pool.js:460:61)
    at Connection.emit (events.js:310:20)
    at Connection.EventEmitter.emit (domain.js:482:12)
    at processMessage (/opt/render/project/src/node_modules/mongodb/lib/core/connection/connection.js:368:10)
    at TLSSocket.<anonymous> (/opt/render/project/src/node_modules/mongodb/lib/core/connection/connection.js:537:15)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
May 16 09:43:47 PM    ok: 0,
May 16 09:43:47 PM    errmsg: 'Cache Reader No keys found for HMAC that is valid for time: { ts: Timestamp(1589645567, 1) } with id: 6771397799096352771',
May 16 09:43:47 PM    code: 211,
May 16 09:43:47 PM    codeName: 'KeyNotFound',
May 16 09:43:47 PM    name: 'MongoError',
May 16 09:43:47 PM    [Symbol(mongoErrorContextSymbol)]: {}
May 16 09:43:47 PM  }
```

**Comment by prastut** [comment]
Possible resource to give vantage on the problem: 
https://github.com/Automattic/mongoose/issues/2874

**Comment by prastut** [comment]
## Testing: 

- [ ] Multiple ws:// -> make it to single API service -> making only 1 subscription to the node. 
- [ ] Instead of 6 hours -> change it to 10 minutes. (Reasonsing: since we know that data updates valuable from YieldScan PoV only happens after 6 hours, we want to increase probability of getting right data)

**Comment by prastut** [comment]
|| strategy: 
1. We ready a dummy database with all features. And have it running on local frontend. 
2. Start testing the API with live data.

**Comment by prastut** [comment]
This seems to have been solved by increasing RAM of the server + node.js process. 

Though we need to stabilize this further by optimizing our MongoDB<-> Mongoose writes. 

Possible solutions here: 
https://itnext.io/performance-tips-for-mongodb-mongoose-190732a5d382

**Comment by prastut** [comment]
Massive spike though no 
![image](https://user-images.githubusercontent.com/10279686/82138110-9051e500-983b-11ea-89f2-0917f0de7f24.png)

Though no writes in logs: 
![image](https://user-images.githubusercontent.com/10279686/82138124-af507700-983b-11ea-8452-abfc7cf6e510.png)

Possibility that this is read spike
